#ifndef ORZ_BASE_PRIVATE_MATH_INCLUDE
#define ORZ_BASE_PRIVATE_MATH_INCLUDE

/// 仅供内部交互信息用
/// 需要使用它的类 base_element

// 声明
enum ElementType
{
	ELEMENT_TYPE_ROOT,
	ELEMENT_TYPE_ERROR,

	ELEMENT_TYPE_WRITER,
	ELEMENT_TYPE_ANIMATE,
	ELEMENT_TYPE_SPRITE,
	ELEMENT_TYPE_CONTROL_TEXT,
	ELEMENT_TYPE_CONTROL_BUTTON,
	ELEMENT_TYPE_CONTROL_BAR,
	ELEMENT_TYPE_CONTROL_LIST
};

enum ElementMessage
{
	ELEMENT_MESSAGE_FUNCTION_ERROR,

	ELEMENT_MESSAGE_MOUSE_OUT,	// 鼠标在元素外
	ELEMENT_MESSAGE_MOUSE_OVER,	// 鼠标在元素内
	ELEMENT_MESSAGE_MOUSE_CONST_DOWN,	// 鼠标在元素内|持续按下
	ELEMENT_MESSAGE_MOUSE_CONST_DOWN_END,// 鼠标在元素内|持续按下结束消息
	ELEMENT_MESSAGE_MOUSE_CLICK,		// 鼠标在元素内|单击
	ELEMENT_MESSAGE_MOUSE_DOUBLE_CLICK	// 鼠标在元素内|双击
};

enum ElementState
{
	ELEMENT_STATE_MOUSE_OVER,
	ELEMENT_STATE_MOUSE_OUT,
	ELEMENT_STATE_MOUSE_DOWN
};

#endif